"""Module for managing graph parameters."""
GRAPH_PARAMETER = {
    "TOP_ENTITIES": 5,
	"ENTITIES_DISTANCE_THRESHOLD": 0.5,
    "MAXIMUM_ENTITIES": 20,
	
    "TOP_ENTITIES_FALLBACK": 15,
	"ENTITIES_DISTANCE_THRESHOLD_FALLBACK": 0.6,
}
